Первое задание диплома
AnnaPustowit/java-explore-with-me pull request #3
Opened 2023-06-19 18:28 UTC by AnnaPustowit

2023-06-21 15:41 UTC, db-exp requested changes

2023-06-21 15:41 UTC, db-exp commented on statistics/statistics-service/src/main/java/ru/practicum/repository/StatsRepository.java
> +public interface StatsRepository extends JpaRepository<Statistics, Long> {
не хватает аннотации Repository

2023-06-21 15:41 UTC, db-exp commented on statistics/statistics-service/src/main/resources/schema.sql
> +    ip        VARCHAR(255)                            NOT NULL,
много - 40 достаточно

2023-06-22 08:52 UTC, AnnaPustowit commented on statistics/statistics-service/src/main/resources/schema.sql
> +    ip        VARCHAR(255)                            NOT NULL,
хорошо, сделаю меньше

2023-06-22 08:52 UTC, AnnaPustowit commented on statistics/statistics-service/src/main/java/ru/practicum/repository/StatsRepository.java
> +public interface StatsRepository extends JpaRepository<Statistics, Long> {
добавила

2023-06-22 08:55 UTC, AnnaPustowit commented on service/pom.xml
> +    <dependencies>
окей, добавлю

2023-06-22 20:09 UTC, db-exp approved these changes

2023-06-22 21:16 UTC, merged