Второй этап задачи
AnnaPustowit/java-explore-with-me pull request #4
Opened 2023-07-01 14:30 UTC by AnnaPustowit

2023-07-01 21:29 UTC, db-exp requested changes

2023-07-01 21:29 UTC, db-exp commented on statistics/statistics-dto/pom.xml
> +            <artifactId>spring-boot-starter-actuator</artifactId>
actuator не очень нужен в dto, но полезен в сервисах

2023-07-01 21:29 UTC, db-exp commented on service/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
Давай еще добавим Transactional, а там, где только чтение из базы Transaction(readOnly=true)

2023-07-01 21:29 UTC, db-exp commented on service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +public class RequestServiceImpl implements RequestService {
предлагаю добавить Transactional

2023-07-01 21:29 UTC, db-exp commented on service/src/main/java/ru/practicum/request/repository/RequestRepository.java
> +public interface RequestRepository extends JpaRepository<Request, Long> {
не хватает аннотации Repository

2023-07-01 21:29 UTC, db-exp commented on service/src/main/java/ru/practicum/event/repository/LocationRepository.java
> +public interface LocationRepository extends JpaRepository<Location, Long> {
не хватает аннотации Repository

2023-07-01 21:29 UTC, db-exp commented on service/src/main/java/ru/practicum/event/repository/EventRepository.java
> +public interface EventRepository extends JpaRepository<Event, Long> {
не хватает аннотации Repository

2023-07-01 21:29 UTC, db-exp commented on service/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:6542/ewm-db
можно переменную среды использовать из docker-compose

2023-07-02 15:44 UTC, AnnaPustowit commented on service/src/main/java/ru/practicum/request/repository/RequestRepository.java
> +public interface RequestRepository extends JpaRepository<Request, Long> {
добавила

2023-07-02 15:45 UTC, AnnaPustowit commented on service/src/main/java/ru/practicum/event/repository/LocationRepository.java
> +public interface LocationRepository extends JpaRepository<Location, Long> {
добавила

2023-07-02 15:45 UTC, AnnaPustowit commented on service/src/main/java/ru/practicum/event/repository/EventRepository.java
> +public interface EventRepository extends JpaRepository<Event, Long> {
добавила

2023-07-02 15:59 UTC, AnnaPustowit commented on service/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
сделала

2023-07-02 15:59 UTC, AnnaPustowit commented on service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +public class RequestServiceImpl implements RequestService {
сделала

2023-07-02 16:11 UTC, AnnaPustowit commented on service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +public class CategoryServiceImpl implements CategoryService {
добавила

2023-07-02 16:33 UTC, AnnaPustowit commented on statistics/statistics-dto/pom.xml
> +            <artifactId>spring-boot-starter-actuator</artifactId>
убрала из дто, в остальных имеется

2023-07-02 16:37 UTC, AnnaPustowit commented on statistics/statistics-service/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:6541/stats-db
можно так оставлю, мне так понятнее

2023-07-02 16:37 UTC, AnnaPustowit commented on service/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:6542/ewm-db
можно так оставлю, мне так понятнее

2023-07-02 16:57 UTC, db-exp approved these changes

2023-07-02 17:45 UTC, merged