Последняя часть задачи
AnnaPustowit/java-explore-with-me pull request #5
Opened 2023-07-06 20:32 UTC by AnnaPustowit

2023-07-07 15:52 UTC, db-exp requested changes

2023-07-07 15:52 UTC, db-exp commented on service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +    private final EventRepository eventRepository;
предлагаю попробовать использовать сервисы, а не репозитории

2023-07-07 15:52 UTC, db-exp commented on service/src/main/java/ru/practicum/comment/dto/CommentRequestDto.java
> +    @NotEmpty String text;
Давай еще Size добавим

2023-07-07 21:07 UTC, AnnaPustowit commented on service/src/main/java/ru/practicum/comment/dto/CommentRequestDto.java
> +    @NotEmpty String text;
size добавила

2023-07-07 21:11 UTC, AnnaPustowit commented on service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +    private final EventRepository eventRepository;
думаю, все же, тут лучше обойтись без экспериментов

2023-07-08 20:09 UTC, db-exp approved these changes

2023-07-12 07:25 UTC, merged